### ISSUE TITLE
Can't use FluentApp as it is in no package

### ISSUE THREAD

**Issue by aless2003** [Eroica/javafx-fluent-theme#1]
Hi, I've found this project yesterday and wanted to give it a try, however, as far as I can tell I can't use the FluentApp class as Java does not have path to import FluentApp as it is in the default package. Aka. No import statement can exist for FluentApp, which results in it being unavailable for me in Java. 
Currently I'm using a workaround by just copying the entire FluentApp class in my own project, but I thought I should probably at least mention it as an issue.

**Comment by ghost** [comment]
Was literally about to open the same issue lol (what a coincidence we both found this project at almost the same time)

But yep I can't use it either ☹️

**Comment by aless2003** [comment]
> Was literally about to open the same issue lol (what a coincidence we both found this project at almost the same time)
> 
> But yep I can't use it either ☹️

Damn I hoped I did something wrong, because this project would really help in reducing Java Apps to stand out in Windows.
I would make a pull request, but I got no idea how I would even start building this correctly and kotlin conventions. Will try if this doesn't get a reply from @Eroica though (which I hope it does).

**Comment by ghost** [comment]
ya, also you should assign @Eroica to the issue

**Comment by aless2003** [comment]
> ya, also you should assign @Eroica to the issue

I don't have that permission, only they have the power to assign anybody to an issue

**Comment by ghost** [comment]
oh my bad

**Comment by Eroica** [comment]
Hello everyone,

sorry for the late reply. It seems (some?) notifications were inactive in my account, so I'm only seeing this issue right now. I'll make sure to update my notification settings next.

I'll ping you @aless2003 now hoping that you receive this message. To set up this theme for your local development, can you try this:

* Clone the repository and run `gradle build` for the `theme` package. If this works, continue to
* building `publishToMavenLocal`. This will create an `.m2` package in your home directory which is basically a local repository. You can then "include" javafx-fluent-theme in your project, like this:
* In your `build.gradle.kts` file where you define dependencies, add `implementation("earth.groundctrl:javafx-fluent-theme:v2023.09a")` (which will use the local repository from the step before).

Alternatively, you should also be able to copy the whole `theme` directory into your project, and setting up Gradle to work with multiple modules: Your `settings.gradle.kts` should contain `include("theme", "your-app-directory")`, and then in `build.gradle.kts` you can write `implementation(project(":theme"))`.

Keep in mind that you still need the DLL file so that the theme works. You can either compile it yourself using Visual Studio 2022 (open the SLN file), or just download it from the Releases and put it into your project directory, which is usually the "root directory" of your project, but to be exact, it is the CWD of your application's process when it is being executed.

Again, I'm terribly sorry that I missed your issue! Please let me know if you have any questions, and I will make sure to double check my account settings.

**Comment by aless2003** [comment]
> Hello everyone,
> 
> sorry for the late reply. It seems (some?) notifications were inactive in my account, so I'm only seeing this issue right now. I'll make sure to update my notification settings next.
> 
> I'll ping you @aless2003 now hoping that you receive this message. To set up this theme for your local development, can you try this:
> 
> * Clone the repository and run `gradle build` for the `theme` package. If this works, continue to
> * building `publishToMavenLocal`. This will create an `.m2` package in your home directory which is basically a local repository. You can then "include" javafx-fluent-theme in your project, like this:
> * In your `build.gradle.kts` file where you define dependencies, add `implementation("earth.groundctrl:javafx-fluent-theme:v2023.09a")` (which will use the local repository from the step before).
> 
> Alternatively, you should also be able to copy the whole `theme` directory into your project, and setting up Gradle to work with multiple modules: Your `settings.gradle.kts` should contain `include("theme", "your-app-directory")`, and then in `build.gradle.kts` you can write `implementation(project(":theme"))`.
> 
> Keep in mind that you still need the DLL file so that the theme works. You can either compile it yourself using Visual Studio 2022 (open the SLN file), or just download it from the Releases and put it into your project directory, which is usually the "root directory" of your project, but to be exact, it is the CWD of your application's process when it is being executed.
> 
> Again, I'm terribly sorry that I missed your issue! Please let me know if you have any questions, and I will make sure to double check my account settings.

Hey, no big deal, I've not had the time to do it myself either. I'll try your suggestions out on the weekend as I'm a little busy with personal stuff right now. Though I'm pretty sure I need to modify the package either way as Java doesn't do "default package" for libraries as there's no path to import it from. Which I assume wasn't all that noticeable in your testing as I assume you mostly write Kotlin, where this works, and not Java where it doesn't. 

Thanks for the reply though, I'll give some feedback when I got everything set up :)

**Comment by Eroica** [comment]
OK, I see the problem now. Putting everything in a flat namespace is a Kotlin convention, but I didn't take into account Java projects. Sorry for the oversight. I just published relase v2024.04 where I organized the source files into packages so that you can import them from Java.

If you build the `theme` project and then "publish" it into your local Maven repository, you should be able to import `FluentApp` now. Here's how I got a Java project working:

`build.gradle`:
```gradle
plugins {
    id 'java'
    id 'application'
    id 'org.openjfx.javafxplugin' version '0.1.0'
}

// ...

repositories {
    mavenLocal() // To get the locally-installed theme
    mavenCentral()
}

// ...

dependencies {
    implementation 'earth.groundctrl:javafx-fluent-theme:v2024.04'

    // ...
}
```

Sample main file:

```java
import earth.groundctrl.fluent.FluentApp;
// ...

public class Main extends FluentApp {
    public Main() {
        super(true, true);
    }

    public static void main(String[] args) {
        launch(args);
    }

    @Override
    public void onCreateStage(@NotNull Stage stage) {
        stage.setTitle("Sample Fluent App");
        stage.setMinWidth(300.0);
        stage.setMinHeight(200.0);

        VBox box = new VBox();
        box.setAlignment(Pos.CENTER);
        box.setPadding(new Insets(16.0, 16.0, 16.0, 16.0));
        box.getChildren().add(new Button("Hello world"));
        box.setStyle("-fx-background: transparent;");

        stage.setScene(new Scene(box, Color.TRANSPARENT));
    }
}
```

![Sample Fluent App](https://github.com/Eroica/javafx-fluent-theme/assets/1134290/b88077c5-aca5-4a19-bd1b-7e6ee6ac428f)

I hope this can help you setting up your project :) Let me know if you find any other incompatibilities, especially with regards to Java projects!

**Comment by aless2003** [comment]
So, two things I noticed:

1. you can't have the version v2024.04, as that is an illegal module name. You will have to change that to reflect a legal module name (e.g 2024_04, 202404) if you want to support Java's module system. 

module names follow the same requirements as package names, which you can see here: https://dev.java/learn/modules/intro/#:~:text=legal%20letters%20include%20A%2DZ%2C%20a%2Dz%2C%200%2D9%2C%20_%2C%20and%20%24%2C%20separated%20by%20.

2. I can't seem to reproduce the look you have in your screenshot. For me it ends up looking like this:
![image](https://github.com/Eroica/javafx-fluent-theme/assets/46018087/50b4f574-fb9b-4687-8af0-051a405f03fe)
Which is probably an issue with how I do something here, not sure what it is though.

**Comment by Eroica** [comment]
`v2024.04` should be the version part of the package. The module itself is called `earth.groundctrl.fluent`. Unfortunately, I was never able to get my Kotlin projects working with https://badass-jlink-plugin.beryx.org/releases/latest/ (as opposed to the Badass Runtime Plugin), so I can't say much about that yet.

For your display issue, can you try what is written here? https://github.com/Eroica/javafx-fluent-theme#issues

So far during my tests, it mainly depends on whether you use an AMD GPU or not. The last line, "If you subclass FluentApp, it will take care of that ..." is probably out-dated, and I should remove it.

To be clear: If the SW switch works for you, then remove it again, and try the two properties in the next paragraph.

**Comment by aless2003** [comment]
Regarding the rendering issue. The fix does not seem to work for me, but again that might be for any number of reasons. I assume it could be thanks to me being in an Insider version of Win 11. I will test it with another PC once I get access to one in the next couple weeks. I use an Nvidia RTX 3080 btw.
I also could confirm that the black background comes from the stage itself, so I assume this is intended to be like that if the stage is Unified.

Regarding the version part. The module is called "javafx-fluent-theme", and it usually appends v2024-04 to the module name as far as I could tell from IntelliJ's error messages and the compilation errors. 

I've also found the following appear in build/publications/maven/module.json, which at least seems to say that the module itself is called "javafx-fluent-theme", sure why it adds the version for me though.
```json
"component": {
    "group": "earth.groundctrl",
    "module": "javafx-fluent-theme",
    "version": "v2024-04",
    "attributes": {
      "org.gradle.status": "release"
    }
  }
  ```

That being said I only rarely use modules, so this might just be a gap in my knowledge, and I do something wrong

**Comment by aless2003** [comment]
One additional thing I should bring up is that the demo app doesn't look any better on my PC, so I assume there's a more underlaying issue with something I did here:
![image](https://github.com/Eroica/javafx-fluent-theme/assets/46018087/4adaed54-1da8-4ec7-a39b-d18ab2637285)

**Comment by Eroica** [comment]
I see, I also encountered the black background on NVIDIA GPUs so just like your setup. Does it look any different on this dev build? https://github.com/Eroica/javafx-fluent-theme/releases/download/dev/demo-dev.zip

The Mica effect is just enabled by setting certain flags and values using `DwmSetWindowAttribute`. I don't know yet whether newer Windows 11 builds changed these values again, but in the meantime you could check whether other projects work on your setup, for example, this Python project: https://github.com/marticliment/win32mica

Alternatively, try the previous "custom_window" project to change your stage's window style (is a little more low-level though): https://github.com/mimoguz/custom_window

If this project can enable Mica on your machine, then we know which Mica values should work, and it's only a matter of (again) getting JavaFX to work with these DWM flags.

**Comment by aless2003** [comment]
> I see, I also encountered the black background on NVIDIA GPUs so just like your setup. Does it look any different on this dev build? https://github.com/Eroica/javafx-fluent-theme/releases/download/dev/demo-dev.zip
> 
> The Mica effect is just enabled by setting certain flags and values using `DwmSetWindowAttribute`. I don't know yet whether newer Windows 11 builds changed these values again, but in the meantime you could check whether other projects work on your setup, for example, this Python project: https://github.com/marticliment/win32mica
> 
> Alternatively, try the previous "custom_window" project to change your stage's window style (is a little more low-level though): https://github.com/mimoguz/custom_window
> 
> If this project can enable Mica on your machine, then we know which Mica values should work, and it's only a matter of (again) getting JavaFX to work with these DWM flags.

The demo dev build definitely works fine for me, as far as I can tell. Here's a picture for reference:
![image](https://github.com/Eroica/javafx-fluent-theme/assets/46018087/6568959a-fe65-4e61-8e9b-b1fc49a441f8)

Moving the Window around it also seems like Mica works fine as well. Do you still want me to check out the other two things? I feel like you got it fixed already

**Comment by Eroica** [comment]
> Do you still want me to check out the other two things?

No it's fine, thanks for checking the dev build. I will do a quick fix to the demo application next, and then I'll have more info about how best to set up the theme (and the `FluentApp` class).

**Comment by Eroica** [comment]
Hi, with the [latest release](https://github.com/Eroica/javafx-fluent-theme/releases/tag/v2024.05), you can now call a static `FluentApp.initialize()` that sets the special flags to make Mica work on non-AMD systems. This should be called as early as possible. I slightly updated the README, hopefully it's a little clearer how to set everything up: https://github.com/Eroica/javafx-fluent-theme?tab=readme-ov-file#usage

The code is organized into packages as well, so hopefully this should work in Java projects too. Let me know if there are any problems!

**Comment by aless2003** [comment]
Hey, sorry, I completely forgot this was not closed yet. I can confirm that it's usable from Java now, which closes this issue for me. I can't get Mica to work in my case (still a black background for my own app), but as everything else seems to work and is probably better addressed in a separate issue, I'll close this anyways. Thanks for your good work and have a good day :)

**Comment by Eroica** [comment]
No problem, if the dev build had working Mica for you, then it should be possible to get it working in your own app. Feel free to open another issue with your code if possible.

My fluent-themed apps were started at different times and have diverged a little bit, so I'm currently working on merging their styles and fixes into this repository. I hope to have another release with new features in the near future.
